<%-- 
    Document   : res
    Created on : Feb 20, 2017, 5:17:11 PM
    Author     : Rohith13
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Result Analysis</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    
    <style>
        #head{ 
        color: tomato;
	font-size: 35px;
        font-weight:bold;
        }
        p{
	padding-left:10px;
	text-align: justify;
        font-size: 20px;
	
        }    
        p1{
            font-size: 20px;
        }
        .panel-heading{
            text-align: center;
            font-weight: bold;
        }
        .panel-body{
            float: left;
            width:50%;
            background-color: #fff;
        }
        #btnText{
            font-weight: bold;
            font-size: 20px;
        }
    </style>
    
    
    <body style="background: antiquewhite">   
    <center><font id="head">Result Analysis</font></center>
    <br>
    <p>
        Result analysis provides a quick way to make an evaluation of pass and fail level in university examinations. The page also helps  
        faculty to compare the examination performance of students of one batch with the performance of other Results of examination 
        under different, semesters and sections are generated by the click of the mouse. The page also provides 
        facility to display the overall pass percentage of the students when compared on various fields.
    </p>
    <div class="panel panel-success">
      <div class="panel-heading">Result Analysis of Students</div>
      <div class="panel-body">
      <form action="overall.jsp" method="post">
          <font id="btnText"> Overall Analysis:</font> <input type="submit" class="btn btn-primary" value="Overall Analysis"/>
      </form>
     </div>
     <div class="panel-body">
        <form action="subject.jsp" method="post"/>
           <font id="btnText"> Subject Wise Analysis: </font><input type="submit"  class="btn btn-primary" value="Subject Wise Analysis"/>
        </form>
     </div>
   </div>
    </body>
</html>
